version: '3.4'

services:
  challenge:
    image: ${DOCKER_REGISTRY-}challengeapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database

  database:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Challenge!password1

  challenge.api:
    image: ${DOCKER_REGISTRY-}challengeapi
    build:
      context: .
      dockerfile: Dockerfile

