version: '3.4'

services:
  challenge.api:
    image: ${DOCKER_REGISTRY-}challengeapi
    build:
      context: .
      dockerfile: src/Challenge.API/Dockerfile
    ports:
      - 45300:80
      - 45301:443
    restart: on-failure
    depends_on:
      - database
    command: sh -c '/wait-for db:1433'
    
  database:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Challenge!password1
    ports:
      - 1433:1433
      