version: '3.4'

services:
  challenge.api:
    image: ${DOCKER_REGISTRY-}challengeapi
    build:
      context: .
      dockerfile: src/Challenge.API/Dockerfile
    ports:
      - 45300:80
      - 45301:443
    networks:
      - challengenetworkd
    restart: on-failure
    depends_on:
      - database
    command: sh -c '/wait-for db:1433'

  database:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Challenge!password1
    ports:
      - 1433:1433
    networks:
      - challengenetworkd

  prometheus:
    image: prom/prometheus
    #restart: always
    ports:
      - 9090:9090
    depends_on:
      - challenge.api
    volumes:
      #- ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - challengenetworkd

  grafana: 
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
    #restart: always
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      #- ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/dashboards:/usr/share/grafana/public/dashboards
      - ./monitoring/grafana/store:/usr/share/grafana/public/app/store
    networks:
      - challengenetworkd

networks:
  challengenetworkd: