apiVersion: 1

datasources:
-  name: 'prometheus'   
   type: prometheus                  
   editable: true                      
   is_default: true                    
   name: 'ChallengeMetrics'                      
   org_id: 1                           
   url: 'http://prometheus:9090'        
   version: 1  