# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.


scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  #- job_name: 'challengelocalhinstance'
  #  metrics_path: '/metrics'
  #  scrape_interval: 10s
  #  static_configs:
  #    - targets: ['host.docker.internal:45300', 'host.docker.internal:45301']
      
  - job_name: 'challenge.api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['challenge.api:80']